# Generated by Django 3.1.4 on 2022-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Mới'), ('Read', 'Đã đọc'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
    ]
