# Generated by Django 3.2.25 on 2024-03-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
